---
title: "Analysis of dependence between Tracking loss and UX"
date: "2023-04-19"
output:
  html_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = 'svg') # set output device to svg
library(tidyverse)

options(width = 150) # https://bookdown.org/yihui/rmarkdown-cookbook/text-width.html
```


# 1- Data loading and preprocessing


```{r}
source("preparingTrackingLossData.R")
source("preparingUXdata.R")
```


```{r}
dataUXTrackingLoss = full_join(
  x = dataTrackingLoss |> select(! all_of("Index")),
  y = dataUX |> mutate(ParticipantID = as.integer(ParticipantID)),
  by = c("ParticipantID", "LocomotionTechnique"),
  suffix = c(".x", ".y"),
  keep = NULL
)
```


# 2- Visualization

```{r}
allQuestionsGroups = unique(data_questions$QuestionGroup)
for (i_QuestionGroup in 1:length(allQuestionsGroups))
{
  nameQuestionGroup = allQuestionsGroups[i_QuestionGroup]
  selectedQuestions = data_questions[
    data_questions$QuestionGroup == nameQuestionGroup, ]
  
  nameQuestions = selectedQuestions$Question_description
  
  df_selectCol = dataUXTrackingLoss[, nameQuestions, drop = FALSE]
  for (i_Question in 1:length(nameQuestions)){
    nameOfQuestion = nameQuestions[i_Question]
    if (selectedQuestions[i_Question, "ToBeInverted"] < 0){
      df_selectCol[, nameOfQuestion] = - df_selectCol[, nameOfQuestion]
    } else if (selectedQuestions[i_Question, "ToBeInverted"] == 0){
      df_selectCol[, nameOfQuestion] = - abs(3 - df_selectCol[, nameOfQuestion])
    }
  }
  
  dataUXTrackingLoss[, nameQuestionGroup] = rowMeans(df_selectCol)
}
```


```{r, fig.height=12, fig.width=12}
dataUXTrackingLoss$NrTrackerlossesOp = - dataUXTrackingLoss$NrTrackerlosses

selectedQuestions = c(allQuestionsGroups, "NrTrackerlossesOp",
                      "I think the virtual speed felt natural compared to normal walking",
                      "I wanted to move through the virtual environment")

corMat = cor(dataUXTrackingLoss[, selectedQuestions], use = "pairwise.complete.obs")
corrplot::corrplot(corMat, order = "hclust")
```


```{r, fig.height=12, fig.width=12}
corTests = dataUXTrackingLoss[, selectedQuestions] |> 
  corrplot::cor.mtest(use = "pairwise.complete.obs")

corrplot::corrplot(corMat, p.mat = corTests$p, sig.level = 0.05, order = "hclust",
                   addrect = 2)
```


# 3- Modeling



