---
title: "Link between number of tracking losses and completion time"
date: "2023-04-15"
output:
  html_document:
    toc: true
    toc_depth: 2
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = 'svg') # set output device to svg
library(tidyverse)
library(lme4)

options(width = 150) # https://bookdown.org/yihui/rmarkdown-cookbook/text-width.html
```


# 1- Data loading and preprocessing


```{r}
source("preparingData.R")

data_all = data_all |>
  mutate(
    completionTimeMin = completionTime / 60,
    NrTrackerlossesPerMin = NrTrackerlosses  / completionTimeMin)
```


# 2- Visualization


```{r}
ggplot(data_all) +
  geom_point(aes(y = NrTrackerlosses, x = completionTimeMin))
```

```{r}
ggplot(data_all) +
  geom_point(aes(y = NrTrackerlosses, x = completionTime)) +
  facet_wrap(~ ParticipantID)
```


```{r}
ggplot(data_all) +
  geom_point(aes(y = NrTrackerlossesPerMin, x = completionTimeMin)) +
  geom_abline(slope = -0.13, intercept = 2.79)
```


# 3- Modeling

```{r}
reg1 <- lmer(data = data_all,
             NrTrackerlosses ~ completionTime + (1 | ParticipantID))

summary(reg1)
```


```{r}
reg1 <- nlme::lme(data = na.omit(data_all),
                  NrTrackerlossesPerMin ~ completionTimeMin,
                  random = ~ 1 | ParticipantID,
                  weights = varConstPower(form=~completionTimeMin))

summary(reg1)
```


