---
title: "Analysis of UX"
date: "2023-04-17"
output:
  html_document:
    toc: true
    toc_depth: 2
---

# In Rstudio go to Tools > Install packages 
# Into the bar type: knitr,tidyverse,lme4,emmeans,gt
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = 'svg') # set output device to svg
library(tidyverse)
library(lmerTest)
library(gt)

options(width = 150) # https://bookdown.org/yihui/rmarkdown-cookbook/text-width.html
```


```{r}
# Adding diagnostics via R session information
print(sessionInfo())
```

```{r}
currentCommit = gitr::get_commit_msgs(n = 1)[[1]]
# Commit message
print(currentCommit[1])
# Commit SHA
print(attr(currentCommit, "sha"))
```


# 1- Data loading and preprocessing

```{r}
source("preparingData.R")
```


# 2- Visualization

```{r}
boxplot(value ~ QuestionName, data = dataUX_pivot)

boxplot(value ~ QuestionGroup, data = dataUX_pivot)

boxplot(value ~ orderCondition, data = dataUX_pivot)
```

```{r, fig.width=10, fig.height=20}
ggplot(dataUX_pivot) +
  geom_jitter(aes(x = orderCondition, y = value), width = 0.1, height = 1,
              pch = ".")

ggplot(dataUX_pivot) +
  geom_jitter(aes(x = orderCondition, y = value), width = 0.1, height = 1) +
  facet_wrap(~ QuestionGroup, ncol = 4)
```


```{r fig.height = 8, fig.width=10}
# Filled box for each combination LocomotionTechnique/QuestionName

dataUX_pivot %>%
  group_by(LocomotionTechnique, QuestionName) %>%
  summarise(averageValue = mean(value, na.rm = TRUE), .groups = "keep") %>%
  ungroup() %>%
  ggplot() +
  geom_tile(aes(x = LocomotionTechnique, y = QuestionName,
                fill = averageValue))

# Filled box for each combination LocomotionTechnique/QuestionGroup

dataUX_pivot %>%
  group_by(LocomotionTechnique, QuestionGroup) %>%
  summarise(averageValue = mean(value, na.rm = TRUE), .groups = "keep") %>%
  ungroup() %>%
  ggplot() +
  geom_tile(aes(x = LocomotionTechnique, y = QuestionGroup, fill = averageValue)) +
  geom_text(aes(x = LocomotionTechnique, y = QuestionGroup, label = round(averageValue, digits = 1))) +
  guides(fill=guide_legend(title="Average Values \n(higher is better)", reverse = TRUE)) +
  xlab("Direction LocomotionTechnique") + ylab("Question Group")
scale_fill_gradient2(
  limits = c(0,100), 
  breaks = seq(0, 100, by = 10), 
  low = "#141414", mid = "#193554", high = "#2dc6fc", midpoint = 50,
)

```


# 3- Modeling


## 3.1 All data


```{r}
my_model = lmer(
  data = dataUX_pivot,
  value ~ LocomotionTechnique * QuestionGroup + orderCondition +
    (1 | ParticipantID) + (1 | QuestionName)
)

summary(my_model)
```

## 3.2 General effect of LocomotionTechnique

```{r}
my_model_emmeans_LocomotionTechnique = emmeans::emmeans(my_model, list(pairwise ~ LocomotionTechnique), adjust = "bonferroni")
#print(my_model_emmeans_LocomotionTechnique)
result <- pairs(my_model_emmeans_LocomotionTechnique, adjust = "bonferroni")

UXConditionTable <- result %>%
  as.data.frame() %>%
  # mutate(`Name of difference` = `1`) %>%
  select(`contrast`, estimate, SE, p.value) %>%
  gt() %>%
  # tail(, -2) %>%
  tab_header(
    title = md("Pairwise comparison **UX scores locomotion techniques**"),
    subtitle = md("`Pvalues` table")
  ) %>% 
  fmt_number(
    columns = p.value, 
    decimals = 10
  )

print(UXConditionTable)

cat(as_latex(UXConditionTable))

```



## 3.3 Differences in LocomotionTechnique by QuestionGroup

```{r}
my_model_emmeans = emmeans::emmeans(my_model, ~ LocomotionTechnique | QuestionGroup)
result = pairs(my_model_emmeans, simple = "LocomotionTechnique", adjust = "bonferroni")
print(result)


```


```{r}
result_df = as.data.frame(result)

mytable = result_df[, c(2, 1, 3, 4, 7)] %>% # this gives the order of columns
  group_by(QuestionGroup) %>%
  gt() |>
  fmt_scientific(
    columns = c(estimate, SE)
  ) |>
  fmt_number(
    columns = p.value, 
    decimals = 4
  )
print(mytable)

cat(as_latex(mytable))
```


# 3.4. Questions on Speed

```{r}
mymodel = lm(data = dataUX_pivot_Speed, 
             value ~ QuestionName * LocomotionTechnique)

my_model_emmeans = emmeans::emmeans(mymodel, ~ LocomotionTechnique | QuestionName)
result = pairs(my_model_emmeans, simple = "LocomotionTechnique")
print(result)

print("Mean conditions too slow/fast compared to natural walking question")
mean(filter(dataUX_pivot_Speed, QuestionName == "I think the virtual speed felt natural compared to normal walking")$value)
print("Mean conditions I wanted to go slower/faster question")
mean(filter(dataUX_pivot_Speed, QuestionName == "I wanted to move through the virtual environment")$value)


result_df = as.data.frame(result)

mytable = result_df[, c(2, 1, 3, 4, 7)] %>% # this gives the order of columns
  group_by(QuestionName) %>%
  gt() |>
  fmt_scientific(
    columns = c(estimate, SE)
  ) |>
  fmt_number(
    columns = p.value, 
    decimals = 4
  )

print(mytable)

cat(as_latex(mytable))
```


# 4. Model the order effects

# 4.1 First approach

```{r}
# This compares hip as 1st experiment to hip as 4th experiment in a subject for each question group.
# By looking up the numbers in the latin square where a condition (hip) was first and last, and noting them in the list, these can be compared below.
grp_Hip1 = c(20, 8, 11, 18, 20)
grp_Hip4 = c(1, 10, 16, 19)
dataUX_pivot = dataUX_pivot %>%
  mutate(grp_Hip = case_when(
    ParticipantID %in% grp_Hip1 ~ 1,
    ParticipantID %in% grp_Hip4 ~ 4
  )) %>%
  mutate(grp_Hip = factor(grp_Hip))

reg1 = lmer(value ~ grp_Hip * QuestionGroup + (1 | ParticipantID) + (1 | QuestionName),
            data = dataUX_pivot |> filter(LocomotionTechnique == "Hip"))

summary(reg1)
```


```{r}
#  comparing hip 1 and 4 per question group:
my_model_emmeans = emmeans::emmeans(reg1, ~ grp_Hip | QuestionGroup)
result = pairs(my_model_emmeans, simple = "grp_Hip", adjust = "bonferroni") #adjust makes no difference here. Is this done correctly?
print(result)
```


# 4.2 Final approach

```{r}
# all data computed in all blocks below looks for a single questionGroup filtered here (VR sickness)
# modelled as direction condition interaction effect with order, considering random effect for participant.
my_model = lmer(
  data = filter(dataUX_pivot, QuestionGroup == "VR Sickness"),
  value ~ LocomotionTechnique * orderCondition +
    (1 | ParticipantID) + (1 | QuestionName)
)

summary(my_model)

model_df <- as.data.frame(coef(summary(my_model)))#[, c(1, 2, 3, 4, 5)]
model_df <- data.frame("names"=rownames(model_df), model_df)
VRsicknessTable <- model_df %>%
  rename(
    `p.value` = `Pr...t..`,
    `Std. Error` = Std..Error
  ) %>%
  select(`names`, Estimate, `Std. Error`, `p.value`) %>%
  gt() %>%
  fmt_number(
    columns = Estimate, 
    decimals = 4
  ) %>%
  fmt_number(
    columns = `Std. Error`, 
    decimals = 4
  ) %>%
  fmt_number(
    columns = `p.value`, 
    decimals = 4
  ) %>%
  # tail(, -2) %>%
  tab_header(
    title = md("Comparison **VR sickness**"),
    subtitle = md("`Pvalues` table")
  ) #%>% 
#as_latex()

print(VRsicknessTable)

cat(as_latex(VRsicknessTable))



```









```{r}
#When looking over all user tests for the Question, there was a significant difference between the first and third experiment on a single subject (p=0.037) and a non-significant difference between first and fourth experiment on a single subject (p=0.0651). 
my_model_emmeans = emmeans::emmeans(my_model, ~ orderCondition )
result = pairs(my_model_emmeans, adjust = "bonferroni")
print(result)
```
```{r} 
# However, the order did not influence the overall UX score comparison between conditions: within a condition there was no significant difference between a direction condition being tested as first, second, third or last (p>0.28).
my_model_emmeans = emmeans::emmeans(my_model, ~ orderCondition | LocomotionTechnique)
result = pairs(my_model_emmeans, adjust = "bonferroni")
print(result)
```


```{r}
dataUX_pivot = dataUX_pivot |>
  mutate(LocomotionTechniqueOrder = paste(LocomotionTechnique, orderCondition, sep = ""))

my_model = lmer(
  data = dataUX_pivot,
  value ~ LocomotionTechnique * QuestionGroup + LocomotionTechniqueOrder +
    (1 | ParticipantID) + (1 | QuestionName)
)

summary(my_model)
```


```{r}
my_model_emmeans = emmeans::emmeans(my_model, ~ LocomotionTechniqueOrder )
result = pairs(my_model_emmeans, adjust="bonferroni")
print(result)
```


```{r}
my_model = lmer(
  data = dataUX_pivot,
  value ~ LocomotionTechnique * QuestionGroup + LocomotionTechnique * orderCondition +
    (1 | ParticipantID) + (1 | QuestionName)
)

summary(my_model)
my_model_emmeans = emmeans::emmeans(my_model, ~ LocomotionTechnique * orderCondition, adjust="bonferroni") # this adjust does nothing, how to do this?
```

```{r, fig.height=8, fig.width=12}
emmeans::pwpp(my_model_emmeans)
```



