---
title: "Analysis of tracking losses"
date: "2023-04-19"
output:
  html_document:
    toc: true
    toc_depth: 2
---
#this file gives the following conclusion: the trackerloss is not significantly different between conditions.


# To install the necessary packages, run:
```{r setup}
#install.packages(c("pbkrtest", "lmerTest", "knitr","tidyverse","lme4","emmeans","ggplot2"))
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = 'svg') # set output device to svg
library(tidyverse)
library(lme4)

options(width = 150) # https://bookdown.org/yihui/rmarkdown-cookbook/text-width.html
```


# 1- Data loading and preprocessing


```{r}
source("preparingTrackingLossData.R")
```


# 2- Visualization

```{r}
# this gives a histogram (y is the number of times a value is present)
ggplot(dataTrackingLoss) +
  geom_histogram(aes(x = NrTrackerlosses), binwidth = 0.5)
```

```{r}
ggplot(dataTrackingLoss) +
  geom_histogram(aes(x = NrTrackerlosses), binwidth = 0.5) +
  facet_wrap(~ ParticipantID)
```

```{r}
ggplot(dataTrackingLoss) +
  geom_histogram(aes(x = NrTrackerlosses), binwidth = 0.5) +
  facet_wrap(~ LocomotionTechnique)
```

# 3- Analysis

```{r}
reg1 <- lmer(data = dataTrackingLoss,
             NrTrackerlosses ~ LocomotionTechnique + (1 | ParticipantID))

summary(reg1)
```

```{r}
my_model_emmeans = emmeans::emmeans(reg1, ~ LocomotionTechnique)
result <- pairs(my_model_emmeans, adjust = "none") #not adjusted. We desire to find insignificance, so we have to be extra strict on concluding any insignificance. If this would be adjusted, we would find insignificant results more easily.

trackingLossTable <- result %>%
  as.data.frame() %>%
  # mutate(`Name of difference` = `1`) %>%
  select(`contrast`, estimate, SE, p.value) %>%
  gt() %>%
  # tail(, -2) %>%
  tab_header(
    title = md("Pairwise comparison **tracking loss locomotion techniques**"),
    subtitle = md("`Pvalues` table")
  ) %>% 
   fmt_number(
    columns = p.value, 
    decimals = 4
  )

print(trackingLossTable)

cat(as_latex(trackingLossTable))
```

```
