---
title: "Analysis of Speed"
date: "2023-04-17"
output:
  html_document:
    toc: true
    toc_depth: 2
---

# In Rstudio go to Tools > Install packages 
# Into the bar type: knitr,tidyverse,lme4,emmeans,gt
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = 'svg') # set output device to svg
library(tidyverse)
library(lmerTest)
library(gt)

options(width = 150) # https://bookdown.org/yihui/rmarkdown-cookbook/text-width.html
```


```{r}
# Adding diagnostics via R session information
print(sessionInfo())
```

```{r}
currentCommit = gitr::get_commit_msgs(n = 1)[[1]]
# Commit message
print(currentCommit[1])
# Commit SHA
print(attr(currentCommit, "sha"))
```


# 1- Data loading and preprocessing

```{r}
source("preparingData.R")
```


# 2- Model

```{r}
mymodel = lm(data = dataUX_pivot_Speed, 
             value ~ QuestionName * LocomotionTechnique)

my_model_emmeans = emmeans::emmeans(mymodel, ~ LocomotionTechnique | QuestionName)
result = pairs(my_model_emmeans, simple = "LocomotionTechnique")
print(result)

print("Mean conditions too slow/fast compared to natural walking question")
mean(filter(dataUX_pivot_Speed, QuestionName == "I think the virtual speed felt natural compared to normal walking")$value)
print("Mean conditions I wanted to go slower/faster question")
mean(filter(dataUX_pivot_Speed, QuestionName == "I wanted to move through the virtual environment")$value)


result_df = as.data.frame(result)

mytable = result_df[, c(2, 1, 3, 4, 7)] %>% # this gives the order of columns
  group_by(QuestionName) %>%
  gt() |>
  fmt_scientific(
    columns = c(estimate, SE)
  ) |>
  fmt_number(
    columns = p.value, 
    decimals = 4
  )

print(mytable)

cat(as_latex(mytable))
```


# 3- Link between perceived speed and order effects

```{r}
reg1 <- lmer(data = data_all,
             `I think the virtual speed felt natural compared to normal walking` 
             ~ orderCondition + (1 | ParticipantID))

summary(reg1)
```

```{r}
my_model_emmeans = emmeans::emmeans(reg1, ~ orderCondition)
result = pairs(my_model_emmeans, simple = "orderCondition", adjust = "none")
print(result)
```


# 4- Link between desired speed and order effects

```{r}
reg1 <- lmer(data = data_all,
             `I wanted to move through the virtual environment` 
             ~ orderCondition + (1 | ParticipantID))

summary(reg1)
```

```{r}
my_model_emmeans = emmeans::emmeans(reg1, ~ orderCondition)
result = pairs(my_model_emmeans, simple = "orderCondition", adjust = "none")
print(result)
```

